title: DATX 
description: Un diccionario de anglecismos y tecnicismos de ciencia de datos y software mexicano.
theme: just-the-docs

url: https://maleniski.github.io/

aux_links:
  Template Repository: hhttps://github.com/Maleniski/diccionario-angl-tec-mx
